### ISSUE TITLE
Add qemu -drive for fstests

### ISSUE THREAD

**Issue by morbidrsa** [rapido-linux/rapido#103]
Currently all of our fstests test cases rely on zram for the test and scratch devs. 

Wouldn't it be a good idea to have a variable in rapdio.conf selecting either zram or an image from qemu?

Another option would be to duplicate the fstests cut and autorun scripts but this sounds like a lot of duplicated work for no reason.

**Update:**
Having the ability to specify more than one external disk would be great. I.e. one for TEST_DEV and one for SCRATCH_DEV or even mulitple for btrfs' SCRATCH_DEV_POOL which is needed for the raid tests.

**Comment by ddiss** [comment]
Sounds reasonable to me. I agree that separate autorun scripts would be unnecessary duplication, but I'm undecided wrt how to best expose this to users.

Could this all be achieved with an extra (optional) `FSTESTS_CONFIG` parameter, with external disks specified via the existing `QEMU_EXTRA_ARGS` parameter?

**Comment by ddiss** [comment]
I've worked on this via https://github.com/rapido-linux/rapido/issues/168 (sorry, forgot about this ticket). A PR which allows fstests devices to be provided via device serial is present at
