### ISSUE TITLE
explicit DRACUT_SRC results in dracut-init.sh: -D: command not found

### ISSUE THREAD

**Issue by ddiss** [rapido-linux/rapido#144]
The rapido.conf `DRACUT_SRC` parameter should allow rapido to be run using Dracut from a specified source tree. When I tried using it with current Dracut HEAD (9e68789d66a6a383e5c46f687350897705c7994f) I encountered:

```
> ./rapido cut lio-local
/home/ddiss/isms/dracut/dracut-init.sh: line 212: -D: command not found
dracut: FAILED: -D .../rapido/initrds/dracut.ebhcfN/initramfs /bin/sh
dracut: Executing: /home/ddiss/isms/dracut/dracut.sh --install "tail blockdev ps rmdir resize dd vim grep find df sha256sum                strace mkfs.xfs truncate losetup dd
dracut: *** Including module: bash ***
/home/ddiss/isms/dracut/dracut-init.sh: line 212: -D: command not found
dracut: FAILED: -D .../rapido/initrds/dracut.ebhcfN/initramfs -l /bin/bash
dracut: *** Including module: udev-rules ***
/home/ddiss/isms/dracut/dracut-init.sh: line 242: -D: command not found
dracut: FAILED: -D .../rapido/initrds/dracut.ebhcfN/initramfs -a -l udevadm cat uname blkid
/home/ddiss/isms/dracut/dracut-init.sh: line 201: -D: command not found
dracut: FAILED: -D .../rapido/initrds/dracut.ebhcfN/initramfs -d /etc/udev
```

@mwilck are you still using this dracut-from-source functionality and have you seen this issue?

**Comment by mwilck** [comment]
Just tried with latest dracut master; I'm not seeing this problem, neither on master (831e310) nor with 9e68789. It seems that `dracut-install` doesn't support the `-D` switch? Perhaps dracut calls the system-installed `DRACUT_INSTALL` rather than the one from your src directory?

**Comment by mwilck** [comment]
Nonsense. It rather looks as if 

```
DRACUT_INSTALL ${dracutsysrootdir:+-r "$dracutsysrootdir"} ${initdir:+-D "$initdir"} ${loginstall:+-L "$loginstall"} ${DRACUT_RESOLVE_DEPS:+-l} ${DRACUT_FIPS_MODE:+-f} ${_hostonly_install:+-H} "$@"
```

expands to `-D .../rapido/initrds/dracut.ebhcfN/initramfs /bin/sh` on your system. So `DRACUT_INSTALL` wasn't found at all. Did you forget to run `make` in the dracut directory?

**Comment by ddiss** [comment]
@mwilck  gah, you're right, I didn't have a complete build. Thanks a lot for taking a look and sorry for the noise

**Comment by mwilck** [comment]
NP :grin:

Btw I finally rebased my code base to the changes you applied during the last 2 years... I hope to be able to submit some additions I've been using soon.
