### ISSUE TITLE
flexible locations for rapido.conf input and initramfs output paths

### ISSUE THREAD

**Issue by ddiss** [rapido-linux/rapido#191]
Rapido currently always assumes that `rapido.conf` (and any associated net-conf) is placed in the rapido parent directory (`RAPIDO_DIR`). Similarly, the Dracut output image is placed at `$RAPIDO_DIR/initrds/myinitrd` (with `dracut --tmpdir` and `qemu -pidfile` using the same directory).
These hardcoded locations are a problem for CI systems, which often run many rapido test jobs simultaneously.
The current workaround for this is to use a separate rapido source directory for each test job, but it's not ideal.

**Comment by pevik** [comment]
OTOH, there is already way to specify different path:

https://github.com/rapido-linux/rapido/blob/6df6408e293cfe521c11e3d52fbd1cdc9352ec4b/runtime.vars#L15

**Comment by ddiss** [comment]
> OTOH, there is already way to specify different path:
> 
> https://github.com/rapido-linux/rapido/blob/6df6408e293cfe521c11e3d52fbd1cdc9352ec4b/runtime.vars#L15

Oops, you're right, that was added for selftest :-)
In that case it's just the remaining hardcoded paths.
