### ISSUE TITLE
Feature: run clone of current system

### ISSUE THREAD

**Issue by hramrach** [rapido-linux/rapido#194]
The rapido setup is needlessly complex.

You already have a system running, booting another copy in qemu should suffice.

**Comment by ddiss** [comment]
> The rapido setup is needlessly complex.

I agree, although I've tried to make getting started as simple as:
`cp rapido.conf.example rapido.conf && ./rapido cut ...`

If you have some more concrete proposals for reducing the complexity, I'm all ears :-).

> You already have a system running, booting another copy in qemu should suffice.

Well, you can boot a clone of the current kernel - you just need to unset `KERNEL_SRC`. It doesn't support cloning the entire rootfs though, if that's what you mean.

**Comment by ddiss** [comment]
> > The rapido setup is needlessly complex.
> 
> I agree, although I've tried to make getting started as simple as: `cp rapido.conf.example rapido.conf && ./rapido cut ...`

Confirmed that this still works fine for the `./rapido cut simple-example` case - networking is a bit more complex, as the `tap` devices need to be configured, I'm open to any suggestions on how to improve things though.

**Comment by hramrach** [comment]
>  It doesn't support cloning the entire rootfs though, if that's what you mean.

It does not need to be cloned, it's already there. qemu supports some fine options like 9pfs for accessing existing filesystems.

If you want to be on the safe side it might be a good idea to mount an overlay over it before passing it to qemu but that's not really necessary.

**Comment by ddiss** [comment]
> > It doesn't support cloning the entire rootfs though, if that's what you mean.
> 
> It does not need to be cloned, it's already there. qemu supports some fine options like 9pfs for accessing existing filesystems.
> 
> If you want to be on the safe side it might be a good idea to mount an overlay over it before passing it to qemu but that's not really necessary.

I suppose we could support this, but I'm not sure it'd improve the complexity / usability situation:
- read-only 9pfs passthrough would leave the corresponding guest paths read-only, and easily allow for conflicts between concurrent host and guest I/O
- write-with-overlay would have the same (or worse) host / guest concurrent access issues, require extra permission for mounting the overlay, and would likely also lead to confusion around file user / group / mode mapping between host and guest
- it'd become much harder to capture / share rapido (kernel+initramfs) images for debugging

With dracut-cpio, Dracut now supports `copy_file_range()` clones/reflinks between source files and cpio archive, so I think that comes close to offering the best of both worlds. 9pfs shares can also be configured via the existing `VIRTFS_SHARE_PATH` option, but they're mostly just used for copying test results from guest to host.

**Comment by ddiss** [comment]
> With dracut-cpio, Dracut now supports `copy_file_range()` clones/reflinks between source files and cpio archive, so I think that comes close to offering the best of both worlds. 9pfs shares can also be configured via the existing `VIRTFS_SHARE_PATH` option, but they're mostly just used for copying test results from guest to host.

Closing with this as justification for now. I'm open to exploring this again if the host->guest passthrough limitations can be addressed, but at this stage I'm quite a fan of the throwaway cpio archive approach for rootfs, especially with dracut-cpio reflinks.

**Comment by hramrach** [comment]
> > > It doesn't support cloning the entire rootfs though, if that's what you mean.
> > 
> > 
> > It does not need to be cloned, it's already there. qemu supports some fine options like 9pfs for accessing existing filesystems.
> > If you want to be on the safe side it might be a good idea to mount an overlay over it before passing it to qemu but that's not really necessary.
> 
> I suppose we could support this, but I'm not sure it'd improve the complexity / usability situation:

The complexity/usability problem is that to run X in rapido you have to figure out
 - the tools used by X (dracut may take care of script interpreters but anything else has to be chased by hand)
 - the libraries used by X and tools used by X (dracut may take care of ELF libraries but not plugins loaded with dlopen or other language libraries like python)
 - the configuration used by the tools and libraries used by X

> * read-only 9pfs passthrough would leave the corresponding guest paths read-only, and easily allow for conflicts between concurrent host and guest I/O

This is not something rapido can and should be solving. Sure, you can do stupid things like delete the running testsuite. You can also delete it while it is being packed into an initramfs. The window is smaller but it's still there.

> * write-with-overlay would have the same (or worse) host / guest concurrent access issues, require extra permission for mounting the overlay, and would likely also lead to confusion around file user / group / mode mapping between host and guest 

There is no more confusion about user/group/mode when it's accessed directly compared to when it's copied into initramfs.

I suppose a default like making . and /tmp writable would work most of the time.

> * it'd become much harder to capture / share rapido (kernel+initramfs) images for debugging

There is nothing to capture when the tool is running from the host directly.

**Comment by ddiss** [comment]
Thanks for the feedback, Michal...

On Fri, 25 Nov 2022 03:56:47 -0800, Michal Suchánek wrote:

> > > > It doesn't support cloning the entire rootfs though, if that's what you mean.  
> > > 
> > > 
> > > It does not need to be cloned, it's already there. qemu supports some fine options like 9pfs for accessing existing filesystems.
> > > If you want to be on the safe side it might be a good idea to mount an overlay over it before passing it to qemu but that's not really necessary.  
> > 
> > I suppose we could support this, but I'm not sure it'd improve the complexity / usability situation:  
> 
> The complexity/usability problem is that to run X in rapido you have to figure out
>  - the tools used by X (dracut may take care of script interpreters but anything else has to be chased by hand)
>  - the libraries used by X and tools used by X (dracut may take care of ELF libraries but not plugins loaded with dlopen or other language libraries like python)
>  - the configuration used by the tools and libraries used by X

All true. Any dependencies that are not ELF libraries or interpreters
need to be explicitly listed in the cut/X script. Likewise,
configuration of test tools is generally performed by the autorun/X
script and wouldn't make much sense to share with the host IMO.

> > * read-only 9pfs passthrough would leave the corresponding guest paths read-only, and easily allow for conflicts between concurrent host and guest I/O  
> 
> This is not something rapido can and should be solving. Sure, you can do stupid things like delete the running testsuite. You can also delete it while it is being packed into an initramfs. The window is smaller but it's still there.

As a dev/test tool, I'm more concerned with how change code + rebuild
will not be possible while a test VM is running without potentially
introducing difficult to diagnose problems.

> > * write-with-overlay would have the same (or worse) host / guest concurrent access issues, require extra permission for mounting the overlay, and would likely also lead to confusion around file user / group / mode mapping between host and guest   
> 
> There is no more confusion about user/group/mode when it's accessed directly compared to when it's copied into initramfs.

I disagree. Root access in the (non-root host process) VM behaves as one
would expect alongside the file modes carried in the cpio archive.

**Comment by hramrach** [comment]
Looking at the rapido architecture it is built a lot around the lists of tools to pull in so this use case would not share all that much with this existing infrastructure.

I guess I will have to roll my own if I want to make it happen.

That said, rapido surely does provide quite some useful examples for building special-purpose ramdisks.

**Comment by hramrach** [comment]
There is a project 'virtme' that does just this.
