### ISSUE TITLE
kselftest: Include test programs in dracut install list

### ISSUE THREAD

**Issue by Werkov** [rapido-linux/rapido#217]
Possible issue: test programs may link to a shared library that would not be copied into the rapido image because dracut would not treat test programs as dynamically linked binaries.

Suggested solution: add test program via `--install` argument, leverage `kselftest-list.txt` file that lists exactly those programs that were built and are installed. (This way no explicit list has to be maintained in the cut config file.)

**Comment by ddiss** [comment]
Thanks for the report. I've tacked on a fix for this to https://github.com/rapido-linux/rapido/pull/214 , tested using the `libcap-ng` linked capabilities tests.
Another simpler option might be to use plain path globbing.
