### ISSUE TITLE
Question: LTP dependencies

### ISSUE THREAD

**Issue by Werkov** [rapido-linux/rapido#221]
LTP cut lists a [number of dependencies](https://github.com/rapido-linux/rapido/blob/master/cut/ltp.sh#L21). When any of the binaries is missing, dracut command will fail (e.g. `Aug 21 14:58:16 host icyci[63764]: dracut-install: ERROR: installing 'attr'`).

There is [LTP package](https://build.opensuse.org/package/view_file/benchmark:ltp:stable/ltp-stable/ltp-stable.spec?expand=1) that recommends some packages -- 1) it means recommendation only, 2) filesystem utils (`mkfs.*`) aren't even recommended.

LTP cut build is hence easily broken with unsatisfied deps. Is the single all-or-nothing install command good?

FWIW, [Dockerfile](https://build.opensuse.org/package/view_file/home:mkoutny:kbuild:containers:build/openSUSE_TW_rapido/Dockerfile?expand=1) listing deps I needed for a successful LTP cut build.

**Comment by ddiss** [comment]
Which version of Dracut are you using? On 15.5 and Tumbleweed (last time I checked), a missing `--install` item won't result in command failure. The `dracut-install` errors for the missing binaries are printed, but the invocation returns successful status.

```
> ./rapido cut -B fstests-xfs 
dracut: Executing: /usr/bin/dracut --install "tail blockdev ps rmdir resize dd vim grep find ...
dracut: *** Including module: udev-rules ***
dracut: Skipping udev rule: 40-redhat.rules
dracut: Skipping udev rule: 50-firmware.rules
dracut: Skipping udev rule: 50-udev.rules
dracut: Skipping udev rule: 91-permissions.rules
dracut: Skipping udev rule: 80-drivers-modprobe.rules
dracut: *** Including module: base ***
dracut: *** Including modules done ***
dracut: *** Installing kernel module dependencies ***
dracut: *** Installing kernel module dependencies done ***
dracut-install: ERROR: installing 'dbench'
dracut-install: ERROR: installing '/usr/share/dbench/client.txt'
dracut-install: ERROR: installing 'duperemove'
dracut: FAILED: /usr/lib/dracut/dracut-install -D /var/tmp/dracut.2wHCbX/initramfs -a /usr/lib/udev/rules.d/54-before-scsi-sg3_id.rules /usr/lib/udev/rules.d/11-dm-parts.rulc
dracut: *** Resolving executable dependencies ***
dracut: *** Resolving executable dependencies done ***
dracut: *** Store current command line parameters ***
dracut: *** Stripping files ***
dracut: *** Stripping files done ***
dracut: *** Creating image file '/home/david/rapido-utils/rapido/initrds/myinitrd' ***
dracut: *** Creating initramfs image file '/home/david/rapido-utils/rapido/initrds/myinitrd' done ***
ERROR: cannot open /dev/sda2: Permission denied
ERROR: not a valid btrfs filesystem: /home
ERROR: cannot open /dev/sda2: Permission denied
ERROR: not a valid btrfs filesystem: /
> echo $?
0
```

**Comment by pevik** [comment]
I also think that missing dependencies does not fail dracut, your error should be something else.

`mkfs.*` are listed in rapido:

https://github.com/rapido-linux/rapido/blob/6d644453be036d385b83cb0b40c8b7783720dd6f/cut/ltp.sh#L18-L26

> There is [LTP package](https://build.opensuse.org/package/view_file/benchmark:ltp:stable/ltp-stable/ltp-stable.spec?expand=1) that recommends some packages -- 1) it means recommendation only, 2) filesystem utils (`mkfs.*`) aren't even recommended.

IMHO in all `mkfs.*` packages are in recommends (`e2fsprogs`, `dosfstools`, `xfsprogs`, `exfatprogs`). The only missing is `btrfsprogs`, because these are installed by default on any SLES/openSUSE tested system (although it'd be better to explicitly list it as well).

FYI We use this package in openqa, where we install with `zypper in --recommends` (https://github.com/os-autoinst/os-autoinst-distri-opensuse/blob/241c52f385c5376d25e971429d425df1fc96e1f4/tests/kernel/install_ltp.pm#L296).

BTW the list of LTP's dependencies in rapido is not complete. But if you test syscalls or cgroups, the dependencies should be fine. I could add more dependencies (e.g. for shell networking tests), but list of dependencies is already quite big.

**Comment by Werkov** [comment]
I use dracut-059+suse.491.g87f19c22-1.1.x86_64
but it's my bad, the failure was because of missing `expect` (I conflated cases when I was adding more packages):
```
dracut-install: ERROR: failed to install '/usr/bin/expect'
dracut[F]: Resolving executable dependencies failed
error: dracut failed
373391d3f6c1:~/kernel # echo $?
1
```
The other listed binaries are not fatal when missing. FTR, when I install all the recommeded packages from LTP specfile (on top of openSUSE TW container), some programs are still missing:
```
dracut-install: ERROR: installing 'mkfs.btrfs'
dracut-install: ERROR: installing 'mkfs.fuse'
dracut-install: ERROR: installing 'mount.btrfs'
dracut-install: ERROR: installing 'mount.ext2'
dracut-install: ERROR: installing 'mount.ext3'
dracut-install: ERROR: installing 'mount.ext4'
dracut-install: ERROR: installing 'mount.ntfs'
dracut-install: ERROR: installing 'mount.vfat'
dracut-install: ERROR: installing 'mount.xfs'
dracut-install: ERROR: installing 'parted'
dracut-install: ERROR: installing 'resize'
dracut-install: ERROR: installing 'xxd'
```

But as was clarified -- this is not fatal (and not needed for all tests). I have the additional deps listed in [the Dockerfile](https://build.opensuse.org/package/view_file/home:mkoutny:kbuild:containers:build/openSUSE_TW_rapido/Dockerfile?expand=1). (The list duplicates existing deps because I generated it semiautomatically.)

I'm closing this question as resolved.
