### ISSUE TITLE
su failing for fstests

### ISSUE THREAD

**Issue by ddiss** [rapido-linux/rapido#224]
As a follow up to https://github.com/rapido-linux/rapido/issues/171 it appears that su is failing on SLE15-SP5.
A bit of stracing shows that it's due to a missing `/etc/security/limits.conf` file.

**Comment by Werkov** [comment]
I think the kernel tests could do with plain `setpriv` (from util-linux) without the complexity of `su` and PAM configuration.

**Comment by ddiss** [comment]
> I think the kernel tests could do with plain `setpriv` (from util-linux) without the complexity of `su` and PAM configuration.

Unfortunately a PAM setup is needed for xfstests, which does things like `echo $cmd | su $user`. https://github.com/rapido-linux/rapido/pull/203 added most of the functionality, but I didn't see any problems with a missing `/etc/security/limits.conf` back then.

**Comment by pevik** [comment]
I wonder if the rest of xfstests community is ok with `su` setup and would not complain about `setpriv`, because replacement with `sed`/`awk` would be simple.

**Comment by ddiss** [comment]
> I wonder if the rest of xfstests community is ok with `su` setup and would not complain about `setpriv`, because replacement with `sed`/`awk` would be simple.

I expect `su` use is a relic that goes back to the days of Irix xfs support. I'll a look at what's needed for setpriv, but will submit the straightforward PAM fix here first.

**Comment by ddiss** [comment]
Fixed via 5bf090745c7cd013d57c8e18ffc7937761661ace .
