### ISSUE TITLE
systemd-network 256.4-2.1 fails to bring up devices

### ISSUE THREAD

**Issue by ddiss** [rapido-linux/rapido#240]
Following a recent Tumbleweed update to `systemd-network-256.4-2.1`, I'm no longer seeing rapido network devices come up. IIRC, this was all working fine with `systemd-network-255.8-1.1`. Nothing stands out immediately from the strace.
(*edit:* I can bring the device up manually with `ip`, so the problem is unlikely to be kernel related)

**Comment by Werkov** [comment]
systemd CI has been recently [oopsing in network setup code](https://github.com/systemd/systemd/actions/runs/10402701847/job/28807710342#step:12:504) when networkctl interacts with TW kernel. Do you spot any oopses in your case too?

**Comment by ddiss** [comment]
> systemd CI has been recently [oopsing in network setup code](https://github.com/systemd/systemd/actions/runs/10402701847/job/28807710342#step:12:504) when networkctl interacts with TW kernel. Do you spot any oopses in your case too?

Interesting. No, I haven't seen anything like that; netlink I/O appears to be working fine. I'll take a closer look today...

**Comment by ddiss** [comment]
Looks like udev interaction. On (broken) Tumbleweed I see:
```
eth0: Saved new link: ifindex=2, iftype=ETHER(1), kind=n/a
eth0: Saved original MTU 1500 (min: 68, max: 65535)
eth0: Saved permanent hardware address: b8:01:98:d6:7b:32
eth0: Saved hardware address: b8:01:98:d6:7b:32
eth0: Saved IPv6 link-local address generation mode: eui64
eth0: Flags change: +MULTICAST +BROADCAST
eth0: link pending udev initialization...
```

Leap 15.6 (working) logs:
```
Found link eth0(2)
eth0: Saved new link: ifindex=2, iftype=ETHER(1), kind=n/a
eth0: Saved original MTU 1500 (min: 68, max: 65535)
eth0: Saved permanent hardware address: b8:01:98:d6:7b:32
eth0: Saved hardware address: b8:01:98:d6:7b:32
eth0: Saved IPv6 link-local address generation mode: eui64
eth0: Flags change: +MULTICAST +BROADCAST
eth0: link has not yet been processed by udev: setup state is n/a.
eth0: udev initialized link
eth0: link has not yet been processed by udev: setup state is pending.
eth0: link has not yet been processed by udev: setup state is pending.
eth0: link has not yet been processed by udev: setup state is pending.
eth0: link has not yet been processed by udev: setup state is pending.
eth0: link has not yet been processed by udev: setup state is pending.
eth0: Found driver: virtio_net
eth0: Link state is up-to-date
eth0: State changed: pending -> initialized
eth0: found matching network '/rapido-rsc/net/vm1/rapido-tap1.network'.
eth0: Configuring with /rapido-rsc/net/vm1/rapido-tap1.network.
eth0: State changed: initialized -> configuring
eth0: link_check_ready(): link is not activated.
eth0: link_check_ready(): link is not activated.
Setting '/proc/sys/net/ipv6/conf/eth0/use_tempaddr' to '0'
Setting '/proc/sys/net/ipv6/conf/eth0/accept_ra' to '0'
Setting '/proc/sys/net/ipv6/conf/eth0/proxy_ndp' to '0'
Setting '/proc/sys/net/ipv4/conf/eth0/promote_secondaries' to '1'
eth0: Requested to set IPv6LL address generation mode
eth0: link_check_ready(): link layer is configuring.
eth0: Requested to activate link
eth0: Requesting static address (n/a): ...
eth0: Setting addresses
...
eth0: link is configured by networkd and online.
```

**Comment by Werkov** [comment]
(The oops will likely be fixed with backport of [fix](https://git.kernel.org/pub/scm/linux/kernel/git/netdev/net.git/commit/?id=d1a7b382a9d3f0f3e5a80e0be2991c075fa4f618) the fix into openSUSE TW (it's queued in git). Yes, it seems unrelated now.)

**Comment by ddiss** [comment]
Bisect points to https://github.com/systemd/systemd/commit/089bef66316e5bdc91b9984148e5a6455449c1da as the culprit for the regression, but I'd expect rapido is somewhat at fault for relying on its "special" udevadm-without-udevd setup.
