### ISSUE TITLE
if libostree is installed, dracut pulls in systemd

### ISSUE THREAD

**Issue by aaptel** [rapido-linux/rapido#46]
After an upgrade/pkg install of my system, libostree was installed and added a /etc/dracut.conf.d/ostree.conf file with the following content:

    add_dracutmodules+=" ostree systemd "

resulting in dracut picking it up automatically by default, which in turn prevented my vm to boot as systemd has some expectations about the system I didn't meet.

The fix was to force-omit ostree and systemd using dracut `-o ostree -o systemd` on the dracut command line.

**Comment by ddiss** [comment]
Thanks for the report. I think it makes sense if we try to ignore all /etc/dracut.conf.d files by specifying "--confdir <some-internal-rapido-path>"

**Comment by ddiss** [comment]
@aaptel please retry with https://github.com/rapido-linux/rapido/pull/47 and report back.
