### ISSUE TITLE
New ceph.conf format parsing

### ISSUE THREAD

**Issue by luis-henrix** [rapido-linux/rapido#71]
Nautilus seems to have slightly changed the ceph.conf format and it causes _ini_parse function to fail parsing it.  The change in question is regarding the monitors section, which can now have a list of IP addresses:
```
 [mon.a]
        mon host =  [192.168.155.1:40880]
```
The '[<addr>:<port>]' is seems to be confusing the parsing code. The same occurs for the global section:
```
[global]
        mon host =  [v2:192.168.155.1:40879,v1:192.168.155.1:40880]
```
I've hacked some code to parse this new config using awk, which should be a bit easier to maintain IMO.  Here's what I currently have:
```
function _ini_parse() {
	local ini_file=$1
	local ini_section=$2
	shift 2
	local ini_key=\"$@\"

	awk -v section="^\\\[$ini_section\\\]" \
		-v key="$ini_key" \
		'$1 ~ section {
			got_section = 1;
			next
		}
		/^\[.*\]/{
			got_section = 0;
			got_key = 0;
		}
		$0 ~ key {
			got_key = 1;
		}
		got_section && got_key && NF {
			print substr($0, index($0, "=") + 1)
			exit 0;
		}' $file
}
```
Would something this be acceptable?  The idea is to actually wrap _ini_parse() with some more high-level functions (such as ceph_get_key, ceph_get_mon_addr...).

**Comment by ddiss** [comment]
Thanks for the report @luis-henrix .

Your awk code does indeed look much easier to maintain. One "feature" I'd like to see retained though is the ability to parse multiple keys in a single section, e.g.
https://github.com/rapido-linux/rapido/blob/master/autorun/samba_cephfs.sh#L28

**Comment by luis-henrix** [comment]
hmm.. Ok, my awk-fu isn't great, so I've really no idea how to actually do that.  OTOH, I was going to propose some extra changes so that scripts wouldn't be calling _ini_parse directly. Instead, they would use a wrapper.  Since all the calls I could find so far simply required to grab a key for a user and a monitor address/port, I was going to propose _ceph_params_get that would grab those 2 params.

Would be it acceptable to add another wrapper to grab the UID/GID too?  Obviously, this wrapper would call _ini_parse twice, so the feature of parsing multiple keys from a single section wouldn't be retained...

**Comment by ddiss** [comment]
Would be it acceptable to add another wrapper to grab the UID/GID too? Obviously, this wrapper would call _ini_parse twice, so the feature of parsing multiple keys from a single section wouldn't be retained...

That sounds fine. Single-pass multi-param support can be added later if needed.
