### ISSUE TITLE
setup br0 failure

### ISSUE THREAD

**Issue by vonnyfly** [rapido-linux/rapido#82]
CentOS 7 report this issue:
```
 $ ip link add br0 type bridge;ip addr add 192.168.155.1/24 dev br0;ip tuntap add dev tap0 
Command line is not complete. Try option "help"
```
The error is from the last command.

**Comment by ddiss** [comment]
Thanks for the report.
It looks like you need to set TAP_USER in rapido.conf .

I'll add an explicit check to br_setup.sh, so that the missing config is detected before ip tuntap invocation.

**Comment by vonnyfly** [comment]
Your patch works. Thanks!

**Comment by ddiss** [comment]
Patch merged, closing...
