### ISSUE TITLE
add shortcut to boot test with one command

### ISSUE THREAD

**Issue by morbidrsa** [rapido-linux/rapido#94]
Currently to run a test the user has to run both a 'rapido cut' and a 'rapido boot' command.

Let's create a shortcut that combines both. This is useful for single VM tests like fstests on a local file-system.

Example:
For my BTRFS smoke testing I have to do:

     ./rapido cut fstests-btrfs && ./rapido boot

 Proposal:

      ./rapido run fstests-btrfs

Optionally a **-s** or **-g** command line parameter for starting a gdb server even if it's not specified in *rapdio.conf* would be good.

**Comment by ddiss** [comment]
Sounds good to me, not so sure about the gdbserver parameters though.
FWIW with the Go u-root based rapidos I added a _-boot=1/0_ parameter for _cut_ which is enabled by default I'd be fine with that approach too:
https://gitlab.com/rapidos/rapidos/blob/master/rapidos.go#L88

**Comment by morbidrsa** [comment]
> Sounds good to me, not so sure about the gdbserver parameters though.

Yeah the gdbserver thingy was just an idea from a debugging session. I wished I had activated the gdbserver, but one can easily drop into qemu monitor and enable the gdbserver from there

> FWIW with the Go u-root based rapidos I added a _-boot=1/0_ parameter for _cut_ which is enabled by default I'd be fine with that approach too:
> https://gitlab.com/rapidos/rapidos/blob/master/rapidos.go#L88

**Comment by ddiss** [comment]
> > Sounds good to me, not so sure about the gdbserver parameters though.
> 
> Yeah the gdbserver thingy was just an idea from a debugging session. I wished I had activated the gdbserver, but one can easily drop into qemu monitor and enable the gdbserver from there

Doesn't QEMU_EXTRA_ARGS (-gdb tcp:127.0.0.1:1234) already suit your needs for this, or do you want to make the decisionon whether to start the gdbserver at boot time?

**Comment by ddiss** [comment]
> Currently to run a test the user has to run both a 'rapido cut' and a 'rapido boot' command.
> 
> Let's create a shortcut that combines both. This is useful for single VM tests like fstests on a local file-system.

@morbidrsa how about something like https://github.com/ddiss/rapido/commit/e1c960b52c99ef08afa67347622f3ff9c49b7ac0 ?

This changes the default behaviour of "cut" to boot the image, unless a -B parameter is provided.

**Comment by morbidrsa** [comment]
Yup looks good, can't test atm as I'm on vacation, sorry.

**Comment by ddiss** [comment]
@morbidrsa thanks for the feedback - pushed. I've been running with this for a week or so.
