### ISSUE TITLE
add hooks for auto-saving test results on shared folder

### ISSUE THREAD

**Issue by morbidrsa** [rapido-linux/rapido#95]
Some autorun scripts, like the fstests and blktests family of autorun scripts, produce a folder with test results.

If a shared folder is configured, sync these results back to the host for later inspection before shutdown.

This could be done by hooking into the *shutdown* function that is implemented in rapido.

**Comment by ddiss** [comment]
I'm all for adding a sync  to the shutdown path, but can't the test results saving be integrated into the test itself, e.g. FSTESTS_AUTORUN_CMD="./check --output /host -g auto"?
Similarly, we could add an `_rt_require_conf_dir VIRTFS_SHARE_PATH` to the cut script so that autorun can assume that a virtfs mount is present at /host .

**Comment by morbidrsa** [comment]
Are you sure fstests' check command has an **-output** option? Mine (git pull from last week) doesn't. I can't see a results, outdir or similar option unfortunately.

**Comment by ddiss** [comment]
> Are you sure fstests' check command has an **-output** option? Mine (git pull from last week) doesn't. I can't see a results, outdir or similar option unfortunately.

It doesn't, I'm just saying that that would IMO be a better location for this functionality.

**Comment by ddiss** [comment]
> > Are you sure fstests' check command has an **-output** option? Mine (git pull from last week) doesn't. I can't see a results, outdir or similar option unfortunately.
> 
> It doesn't, I'm just saying that that would IMO be a better location for this functionality.

In the meantime it would also be possible to just tack the /host copy logic onto the end of FSTESTS_AUTORUN_CMD .

**Comment by ddiss** [comment]
I think existing `VIRTFS_SHARE_PATH` behaviour, coupled with the new post-autorun script functionality added via https://github.com/rapido-linux/rapido/pull/146 should provide enough in the way of hooks to achieve this goal. Please reopen if you disagree.
